language:
  - cpp
  - python
python:
  - "2.7"
compiler:
  - gcc
env:
  #- ROS_DISTRO=groovy ROSWS=rosws  BUILDER=rosbuild  USE_DEB=true
  #- ROS_DISTRO=groovy ROSWS=rosws  BUILDER=rosbuild  USE_DEB=false
  - ROS_DISTRO=groovy ROSWS=wstool BUILDER=catkin    USE_DEB=true
  - ROS_DISTRO=groovy ROSWS=wstool BUILDER=catkin    USE_DEB=false
  - ROS_DISTRO=hydro  ROSWS=wstool BUILDER=catkin    USE_DEB=true
  - ROS_DISTRO=hydro  ROSWS=wstool BUILDER=catkin    USE_DEB=false
  - ROS_DISTRO=indigo  ROSWS=wstool BUILDER=catkin   USE_DEB=true
  - ROS_DISTRO=indigo  ROSWS=wstool BUILDER=catkin   USE_DEB=false
matrix:
  allow_failures:
    - env: ROS_DISTRO=indigo  ROSWS=wstool BUILDER=catkin   USE_DEB=true
    - env: ROS_DISTRO=indigo  ROSWS=wstool BUILDER=catkin   USE_DEB=false
before_install: # Use this to prepare the system to install prerequisites or dependencies
  - sudo sh -c 'echo "deb http://packages.ros.org/ros/ubuntu precise main" > /etc/apt/sources.list.d/ros-latest.list'
  - wget http://packages.ros.org/ros.key -O - | sudo apt-key add -
  - sudo apt-get update -qq
install:
  - if [ $ROS_DISTRO = groovy ]; then sudo apt-get install -qq -y ros-$ROS_DISTRO-audio-common ros-$ROS_DISTRO-navigation ros-$ROS_DISTRO-pr2-common ros-$ROS_DISTRO-pr2-controllers; fi
script: source .travis/travis.sh

